import Head from "next/head"
import {useResizeDetector} from "react-resize-detector";
import GWHeader from "../components/organisms/GWHeader";
import Div from "../components/styled/Div";
import FlexContainer from "../components/styled/FlexContainer";
import GWFooter from "../components/organisms/GWFooter";
import {ColorModeContextProvider} from "../contexts/ColorModeContext";
import Container from "../components/styled/Container";
import GWStepCard from "../components/molecules/GWStepCard";

const Demo2 = (props) => {
    const { width, height, ref } = useResizeDetector()
    const items = [
        {
            title: "Select a precious metal & vault",
            description: "See the real time market spot prices of precious metal how it works points image.",
            selected: true
        },
        {
            title: "Select a precious metal & vault",
            description: "See the real time market spot prices of precious metal how it works points image.",
            selected: false
        },
        {
            title: "Select a precious metal & vault",
            description: "See the real time market spot prices of precious metal how it works points image.",
            selected: false
        },
        {
            title: "Select a precious metal & vault",
            description: "See the real time market spot prices of precious metal how it works points image.",
            selected: false
        }
    ]

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main style={{ width: "100%" }} ref={ref}>
                <GWHeader />
                <Container sx={{ background: "#F5F5F5" }}>
                    <Div className="row" sx={{ paddingTop: "100px" }}>
                        <FlexContainer className="col-md-8 mx-auto">
                            <FlexContainer sx={{ alignItems: "center", justifyContent:"flex-start", flexDirection:"column" }}>
                                {
                                    items && items.map((i, index) =>
                                    <GWStepCard
                                        selected={i.selected}
                                        stepNumber={index+1}
                                        title={i.title}
                                        description={i.description}
                                    />)
                                }
                            </FlexContainer>
                        </FlexContainer>
                    </Div>
                </Container>
                <GWFooter />
            </main>
        </>
    )
};

Demo2.getLayout = function getLayout(page) {
    return (
        <ColorModeContextProvider>
            {page}
        </ColorModeContextProvider>
    )
}

export default Demo2;
